import React,{useMemo,useState}from'react';
import{SafeAreaView,View,Text,TouchableOpacity,ScrollView,StyleSheet}from'react-native';
import{CameraView,useCameraPermissions}from'expo-camera';
import{StatusBar}from'expo-status-bar';
import{RANKS,SUITS,parseCard,equity}from'./src/poker';

const slots=['Joueur 1','Joueur 2','Flop 1','Flop 2','Flop 3','Turn','River'];
export default function App(){
 const[perm,ask]=useCameraPermissions();const[camera,setCamera]=useState(false);const[cards,setCards]=useState(Array(7).fill(null));const[sel,setSel]=useState(0);const[rank,setRank]=useState('A');
 const hero=cards.slice(0,2).filter(Boolean).map(parseCard),board=cards.slice(2).filter(Boolean).map(parseCard);
 const eq=useMemo(()=>hero.length===2&&board.length>=3?equity(hero,board):null,[cards]);
 const chooseSuit=s=>{const id=rank+s;if(cards.includes(id)&&cards[sel]!==id)return;const n=[...cards];n[sel]=id;setCards(n);if(sel<6)setSel(sel+1)};
 const openCamera=async()=>{if(!perm?.granted){const r=await ask();if(!r.granted)return;}setCamera(true)};
 if(camera)return <View style={{flex:1,backgroundColor:'#000'}}><CameraView style={{flex:1}} facing="back"/><SafeAreaView style={styles.overlay}><Text style={styles.camTitle}>CADRAGE CAMÉRA</Text><Text style={styles.camHelp}>Vise l'écran du jeu. Cette build valide d'abord le moteur et le cadrage. La reconnaissance automatique des cartes sera activée après calibration sur ton écran réel.</Text><TouchableOpacity style={styles.close} onPress={()=>setCamera(false)}><Text style={styles.btnText}>Revenir à l'analyse</Text></TouchableOpacity></SafeAreaView></View>;
 return <SafeAreaView style={styles.root}><StatusBar style="light"/><ScrollView contentContainerStyle={styles.body}><Text style={styles.title}>LEXOS</Text><Text style={styles.sub}>Poker Analyzer · V0.5.1</Text><TouchableOpacity style={styles.camera} onPress={openCamera}><Text style={styles.btnText}>📷 Ouvrir la caméra</Text></TouchableOpacity>
 <Text style={styles.section}>Cartes reconnues / saisie de contrôle</Text><View style={styles.slots}>{slots.map((x,i)=><TouchableOpacity key={x} onPress={()=>setSel(i)} style={[styles.slot,sel===i&&styles.active]}><Text style={styles.slotLabel}>{x}</Text><Text style={[styles.card,cards[i]&&(cards[i].includes('♥')||cards[i].includes('♦'))&&styles.red]}>{cards[i]||'—'}</Text></TouchableOpacity>)}</View>
 <Text style={styles.pick}>Rang</Text><View style={styles.row}>{RANKS.map(r=><TouchableOpacity key={r} onPress={()=>setRank(r)} style={[styles.small,rank===r&&styles.active]}><Text style={styles.smallText}>{r}</Text></TouchableOpacity>)}</View><Text style={styles.pick}>Couleur</Text><View style={styles.row}>{SUITS.map(s=><TouchableOpacity key={s} onPress={()=>chooseSuit(s)} style={styles.suit}><Text style={[styles.suitText,(s==='♥'||s==='♦')&&styles.red]}>{s}</Text></TouchableOpacity>)}</View>
 <View style={styles.result}>{eq?<><Text style={styles.resultTitle}>Situation mathématique exacte</Text><Text style={styles.win}>GAIN {(eq.win*100).toFixed(2)} %</Text><Text style={styles.tie}>ÉGALITÉ {(eq.tie*100).toFixed(2)} %</Text><Text style={styles.lose}>PERTE {(eq.lose*100).toFixed(2)} %</Text><Text style={styles.samples}>{eq.total.toLocaleString('fr-FR')} états énumérés</Text></>:<Text style={styles.wait}>Entre 2 cartes joueur + au moins le flop pour lancer le calcul exact.</Text>}</View><TouchableOpacity onPress={()=>setCards(Array(7).fill(null))}><Text style={styles.reset}>Réinitialiser la main</Text></TouchableOpacity></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#07110d'},body:{padding:18,paddingBottom:50},title:{fontSize:34,fontWeight:'900',color:'#7df0b2',letterSpacing:5,textAlign:'center'},sub:{color:'#91a89d',textAlign:'center',marginBottom:18},camera:{backgroundColor:'#16784a',padding:15,borderRadius:14,alignItems:'center'},btnText:{color:'white',fontWeight:'800'},section:{color:'white',fontWeight:'800',fontSize:17,marginTop:22,marginBottom:10},slots:{flexDirection:'row',flexWrap:'wrap',gap:7},slot:{width:'23%',minWidth:72,backgroundColor:'#11221a',borderWidth:1,borderColor:'#284536',borderRadius:10,padding:8,alignItems:'center'},active:{borderColor:'#65e8a4',borderWidth:2},slotLabel:{fontSize:10,color:'#91a89d'},card:{fontSize:22,fontWeight:'900',color:'white',marginTop:4},red:{color:'#ff6677'},pick:{color:'#91a89d',marginTop:16,marginBottom:6},row:{flexDirection:'row',flexWrap:'wrap',gap:5},small:{backgroundColor:'#11221a',borderRadius:7,paddingVertical:8,paddingHorizontal:10},smallText:{color:'white',fontWeight:'700'},suit:{backgroundColor:'#f4f4ef',borderRadius:9,padding:10,minWidth:50,alignItems:'center'},suitText:{fontSize:25,color:'#111'},result:{backgroundColor:'#0d1d16',borderRadius:16,padding:18,marginTop:22,borderWidth:1,borderColor:'#284536'},resultTitle:{color:'white',fontWeight:'800',marginBottom:10},win:{color:'#6ff0aa',fontSize:24,fontWeight:'900'},tie:{color:'#e9c85f',fontSize:18,fontWeight:'800'},lose:{color:'#ff7886',fontSize:18,fontWeight:'800'},samples:{color:'#91a89d',marginTop:8},wait:{color:'#91a89d',lineHeight:20},reset:{color:'#7df0b2',textAlign:'center',marginTop:20},overlay:{position:'absolute',left:15,right:15,bottom:25,backgroundColor:'#07110ddd',padding:16,borderRadius:15},camTitle:{color:'#7df0b2',fontWeight:'900',fontSize:18},camHelp:{color:'white',marginVertical:10,lineHeight:19},close:{backgroundColor:'#16784a',padding:13,borderRadius:10,alignItems:'center'}});
